---

- name: Ensure kuma paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ uptime_kuma_uid }}"
    group: "{{ uptime_kuma_gid }}"
  with_items:
    - "{{ uptime_kuma_base_path }}"
    - "{{ uptime_kuma_data_path }}"

- name: Ensure uptime-kuma support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ uptime_kuma_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ uptime_kuma_uid }}"
    group: "{{ uptime_kuma_gid }}"
  with_items:
    - env
    - labels

- name: Ensure kuma container image is pulled
  community.docker.docker_image:
    name: "{{ uptime_kuma_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ uptime_kuma_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else uptime_kuma_container_image_force_pull }}"

- name: Ensure uptime-kuma container network is created
  community.general.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ uptime_kuma_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure uptime-kuma systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/uptime-kuma.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ uptime_kuma_identifier }}.service"
    mode: "0644"
